VALID_PLAN_STATES = ["DRAFT","UNDER_REVIEW","APPROVED","PUBLISHED","REVISION_REQUESTED","SUPERSEDED","REJECTED"]
VALID_BLOCK_STATES = ["GENERATED","UNDER_REVIEW","APPROVED","PUBLISHED","IN_PROGRESS","COMPLETED","PARTIALLY_COMPLETED","CANCELLED","REJECTED"]
VALID_TASK_STATES = ["ELIGIBLE","SCHEDULED","LOCKED","IN_PROGRESS","COMPLETED","PARTIALLY_COMPLETED","DEFERRED","CANCELLED","PENDING","VALIDATION_FAILED"]

TRANSITIONS = {
    "DRAFT": ["UNDER_REVIEW","REJECTED"],
    "UNDER_REVIEW": ["APPROVED","REJECTED","DRAFT"],
    "APPROVED": ["PUBLISHED","SUPERSEDED"],
    "PUBLISHED": ["SUPERSEDED","REVISION_REQUESTED"],
}

def can_transition(current, target):
    if current == target:
        return True
    return target in TRANSITIONS.get(current, [])

def is_editable_status(status):
    return status == "DRAFT"

def is_immutable_status(status):
    return status in ["APPROVED","PUBLISHED","SUPERSEDED"]
